version: '3.7'

    services:
      postgresql-server:
        image: postgres:latest
        container_name: postgresql-server
        restart: unless-stopped
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        volumes:
          - postgresql-data:/var/lib/postgresql/data
        networks:
          custom_network:
            ipv4_address: 172.55.0.2

      zabbix-server:
        build:
          context: .
          dockerfile: Dockerfile.zabbix-server-pgsql
        container_name: zabbix-server
        restart: unless-stopped
        depends_on:
          - postgresql-server
        environment:
          DB_SERVER_HOST: postgresql-server
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - "10051:10051"
        volumes:
          - zabbix-server-data:/var/lib/zabbix
          - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
          - zabbix-export-data:/var/lib/zabbix/export
        networks:
          custom_network:
            ipv4_address: 172.55.0.3

      zabbix-web-nginx-pgsql:
        image: zabbix/zabbix-web-nginx-pgsql:latest
        container_name: zabbix-web
        restart: unless-stopped
        depends_on:
          - postgresql-server
          - zabbix-server
        environment:
          DB_SERVER_HOST: postgresql-server
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          ZBX_SERVER_HOST: zabbix-server
          PHP_TZ: ${PHP_TZ}
        ports:
          - "${ZABBIX_FRONTEND_PORT}:8080"
        volumes:
          - zabbix-web-data:/usr/share/zabbix
        networks:
          custom_network:
            ipv4_address: 172.55.0.4

      zabbix-agent:
        image: zabbix/zabbix-agent2
        container_name: zabbix-agent
        restart: unless-stopped
        depends_on:
          - zabbix-server
        environment:
          ZBX_HOSTNAME: "zabbix-server"
          ZBX_SERVER_HOST: zabbix-server
          ZBX_SERVER_PORT: '10051'
          ZBX_SERVER_ACTIVE: zabbix-server
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        privileged: true
        networks:
          custom_network:
            ipv4_address: 172.55.0.5

    volumes:
      postgresql-data:
      zabbix-server-data:
      zabbix-snmptraps-data:
      zabbix-export-data:
      zabbix-web-data:

    networks:
      custom_network:
        driver: bridge
        ipam:
          config:
            - subnet: 172.55.0.0/16

